/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.GoiMonBUS;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Huynh Hy Qui
 */
public class OrderFrm extends javax.swing.JFrame {
    static int countDB;
    static int countLON;
    static int countNHO;
    static int countQuay;
    static int countHG;
    static int countBP;
    static int countTiet;
    static int countTHG;
    static int countThit;
    Random rd = new Random();
    long tongtien;

    /**
     * Creates new form OrderFrm
     */
    public OrderFrm() {
        initComponents();
        setLocationRelativeTo(null);
        Random rd = new Random();
        int n = rd.nextInt(999999);
        lbSP.setText(n+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBan = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbDB = new javax.swing.JLabel();
        btnUpDB = new javax.swing.JButton();
        btnDownDB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDownLON = new javax.swing.JButton();
        btnUpLON = new javax.swing.JButton();
        btnDownNHO = new javax.swing.JButton();
        btnUpNHO = new javax.swing.JButton();
        lbLON = new javax.swing.JLabel();
        lbNHO = new javax.swing.JLabel();
        lbTongDB = new javax.swing.JLabel();
        lbTongLON = new javax.swing.JLabel();
        lbTongNHO = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnDownQuay = new javax.swing.JButton();
        btnDownHG = new javax.swing.JButton();
        btnDownBP = new javax.swing.JButton();
        btnDownTiet = new javax.swing.JButton();
        btnDownTHG = new javax.swing.JButton();
        btnDownThit = new javax.swing.JButton();
        lbQuay = new javax.swing.JLabel();
        btnUpQuay = new javax.swing.JButton();
        btnUpHG = new javax.swing.JButton();
        btnUpBP = new javax.swing.JButton();
        btnUpTiet = new javax.swing.JButton();
        btnUpThit = new javax.swing.JButton();
        btnUpTHG = new javax.swing.JButton();
        lbHG = new javax.swing.JLabel();
        lbBP = new javax.swing.JLabel();
        lbTiet = new javax.swing.JLabel();
        lbTHG = new javax.swing.JLabel();
        lbThit = new javax.swing.JLabel();
        lbTongQuay = new javax.swing.JLabel();
        lbTongHG = new javax.swing.JLabel();
        lbTongBP = new javax.swing.JLabel();
        lbTongTiet = new javax.swing.JLabel();
        lbTongTHG = new javax.swing.JLabel();
        lbTongThit = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lbSP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GỌI MÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Số phiếu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bàn");

        txtBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBan.setForeground(new java.awt.Color(255, 0, 0));
        txtBan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBanFocusLost(evt);
            }
        });

        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_order_history_48px.png"))); // NOI18N
        btnOrder.setText("GỌI MÓN");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MÓN CHÍNH");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tô phở đặc biệt (75.000 VND)");

        lbDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDB.setText("0");

        btnUpDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpDBActionPerformed(evt);
            }
        });

        btnDownDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownDBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tô phở lớn (60.000 VND)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tô phở nhỏ (45.000 VND)");

        btnDownLON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownLON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownLONActionPerformed(evt);
            }
        });

        btnUpLON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpLON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpLONActionPerformed(evt);
            }
        });

        btnDownNHO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownNHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownNHOActionPerformed(evt);
            }
        });

        btnUpNHO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpNHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpNHOActionPerformed(evt);
            }
        });

        lbLON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLON.setText("0");

        lbNHO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNHO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNHO.setText("0");

        lbTongDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongDB.setText("0");

        lbTongLON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongLON.setText("0");

        lbTongNHO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongNHO.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDownDB, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnDownLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDB, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lbLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpDB, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongDB, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbTongLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownDB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnUpDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDownLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTongLON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongNHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongTien.setText("0");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)), "MÓN THÊM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Quẩy (5.000 VND)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Hột gà (5.000 VND)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Bánh phở (10.000 VND)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tiết (10.000 VND)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Tiết hột gà (15.000 VND)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Thịt (25.000 VND)");

        btnDownQuay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownQuayActionPerformed(evt);
            }
        });

        btnDownHG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownHG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownHGActionPerformed(evt);
            }
        });

        btnDownBP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownBPActionPerformed(evt);
            }
        });

        btnDownTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownTietActionPerformed(evt);
            }
        });

        btnDownTHG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownTHG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownTHGActionPerformed(evt);
            }
        });

        btnDownThit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_down_16px.png"))); // NOI18N
        btnDownThit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownThitActionPerformed(evt);
            }
        });

        lbQuay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuay.setText("0");

        btnUpQuay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpQuayActionPerformed(evt);
            }
        });

        btnUpHG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpHG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpHGActionPerformed(evt);
            }
        });

        btnUpBP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpBPActionPerformed(evt);
            }
        });

        btnUpTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpTietActionPerformed(evt);
            }
        });

        btnUpThit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpThit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpThitActionPerformed(evt);
            }
        });

        btnUpTHG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_up_16px.png"))); // NOI18N
        btnUpTHG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpTHGActionPerformed(evt);
            }
        });

        lbHG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHG.setText("0");

        lbBP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBP.setText("0");

        lbTiet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTiet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTiet.setText("0");

        lbTHG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTHG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTHG.setText("0");

        lbThit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbThit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThit.setText("0");

        lbTongQuay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongQuay.setText("0");

        lbTongHG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongHG.setText("0");

        lbTongBP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongBP.setText("0");

        lbTongTiet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongTiet.setText("0");

        lbTongTHG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongTHG.setText("0");

        lbTongThit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTongThit.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDownQuay, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnDownHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownTHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbQuay, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lbHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpTHG, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnUpThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpQuay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongQuay, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(lbTongHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongTHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDownQuay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpQuay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbQuay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongQuay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDownHG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDownBP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpBP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTongTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDownTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUpTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTongTHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDownTHG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnUpTHG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTHG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(btnDownThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongThit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Tổng tiền");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_48px.png"))); // NOI18N
        btnCancel.setText("HỦY BỎ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lbSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbSPFocusLost(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checked_radio_button_64px.png"))); // NOI18N
        jButton1.setText("KIỂM TRA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSP, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnOrder)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(lbSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBan))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        String ban = txtBan.getText();
        int sobanban=Integer.parseInt(txtBan.getText());
        int a = Integer.parseInt(lbDB.getText());
        int b = Integer.parseInt(lbLON.getText());
        int c = Integer.parseInt(lbNHO.getText());
        int d = Integer.parseInt(lbQuay.getText());
        int e = Integer.parseInt(lbHG.getText());
        int f = Integer.parseInt(lbBP.getText());
        int g = Integer.parseInt(lbTiet.getText());
        int h = Integer.parseInt(lbTHG.getText());
        int i = Integer.parseInt(lbThit.getText());
        if (ban.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số bàn !");
        }
        else if (GoiMonBUS.checkBan(ban)){
            JOptionPane.showMessageDialog(rootPane, "Bàn có khách !");
            txtBan.requestFocus();
        }
        else if (sobanban < 1 || sobanban > 30){
            JOptionPane.showMessageDialog(rootPane, "Bàn không hợp lệ");
            txtBan.requestFocus();
        }
        else {
            if (a > 0) {
                if (GoiMonBUS.ghiToDB(lbSP.getText(), lbDB.getText(), lbTongDB.getText())) {

                }
            }
            if (b > 0){
                if (GoiMonBUS.ghiToLon(lbSP.getText(), lbLON.getText(), lbTongLON.getText())){
                    
                }
            }
            if (c > 0) {
                if (GoiMonBUS.ghiToNho(lbSP.getText(), lbNHO.getText(), lbTongNHO.getText())) {

                }
            }
            if (d > 0) {
                if (GoiMonBUS.ghiToQuay(lbSP.getText(), lbQuay.getText(), lbTongQuay.getText())) {

                }
            }
            if (e > 0) {
                if (GoiMonBUS.ghiToHotGa(lbSP.getText(), lbHG.getText(), lbTongHG.getText())) {

                }
            }
            if (f > 0) {
                if (GoiMonBUS.ghiToBanhPho(lbSP.getText(), lbBP.getText(), lbTongBP.getText())) {

                }
            }
            if (g > 0) {
                if (GoiMonBUS.ghiToTiet(lbSP.getText(), lbTiet.getText(), lbTongTiet.getText())) {

                }
            }
            if (h > 0) {
                if (GoiMonBUS.ghiToTietHotGa(lbSP.getText(), lbTHG.getText(), lbTongTHG.getText())) {

                }
            }
            if (i > 0) {
                if (GoiMonBUS.ghiToThit(lbSP.getText(), lbThit.getText(), lbTongThit.getText())) {

                }
            }
            if (GoiMonBUS.ghiHoaDon(lbSP.getText(), txtBan.getText()) == true) {
                if (GoiMonBUS.banCoKhach(txtBan.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Thành công");
                    txtBan.setText("");
                    txtBan.requestFocus();
                    lbDB.setText(0+"");
                    lbLON.setText(0+"");
                    lbNHO.setText(0+"");
                    lbQuay.setText(0+"");
                    lbHG.setText(0+"");
                    lbBP.setText(0+"");
                    lbTiet.setText(0+"");
                    lbTHG.setText(0+"");
                    lbThit.setText(0+"");
                    lbTongDB.setText(0+"");
                    lbTongLON.setText(0+"");
                    lbTongNHO.setText(0+"");
                    lbTongQuay.setText(0+"");
                    lbTongHG.setText(0+"");
                    lbTongBP.setText(0+"");
                    lbTongTiet.setText(0+"");
                    lbTongTHG.setText(0+"");
                    lbTongThit.setText(0+"");
                    Random rd = new Random();
                    int n = rd.nextInt(999999);
                    lbSP.setText(n + "");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed");
            }
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnUpDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpDBActionPerformed
        lbDB.setText((++countDB)+"");
        long tong=75000*countDB;
        lbTongDB.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpDBActionPerformed

    private void btnDownDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownDBActionPerformed
        int a = Integer.parseInt(lbDB.getText());
        long tong;
        if (a==0){
            lbDB.setText(countDB+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbDB.setText((--countDB)+"");
            tong=75000*countDB;
            lbTongDB.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownDBActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpLONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpLONActionPerformed
        lbLON.setText((++countLON)+"");
        long tong=60000*countLON;
        lbTongLON.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpLONActionPerformed

    private void btnUpNHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpNHOActionPerformed
        lbNHO.setText((++countNHO)+"");
        long tong=45000*countNHO;
        lbTongNHO.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpNHOActionPerformed

    private void btnDownLONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownLONActionPerformed
        int a = Integer.parseInt(lbLON.getText());
        long tong;
        if (a==0){
            lbLON.setText(countLON+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbLON.setText((--countLON)+"");
            tong=60000*countLON;
            lbTongLON.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownLONActionPerformed

    private void btnDownNHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownNHOActionPerformed
        int a = Integer.parseInt(lbNHO.getText());
        long tong;
        if (a==0){
            lbNHO.setText(countNHO+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbNHO.setText((--countNHO)+"");
            tong=45000*countNHO;
            lbTongNHO.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownNHOActionPerformed

    private void btnUpQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpQuayActionPerformed
        lbQuay.setText((++countQuay)+"");
        long tong=5000*countQuay;
        lbTongQuay.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpQuayActionPerformed

    private void btnUpHGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpHGActionPerformed
        lbHG.setText((++countHG)+"");
        long tong=5000*countHG;
        lbTongHG.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpHGActionPerformed

    private void btnUpBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpBPActionPerformed
        lbBP.setText((++countBP)+"");
        long tong=10000*countBP;
        lbTongBP.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpBPActionPerformed

    private void btnUpTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpTietActionPerformed
        lbTiet.setText((++countTiet)+"");
        long tong=10000*countTiet;
        lbTongTiet.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpTietActionPerformed

    private void btnUpTHGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpTHGActionPerformed
        lbTHG.setText((++countTHG)+"");
        long tong=15000*countTHG;
        lbTongTHG.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpTHGActionPerformed

    private void btnUpThitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpThitActionPerformed
        lbThit.setText((++countThit)+"");
        long tong=25000*countThit;
        lbTongThit.setText(tong+"");
        tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
        lbTongTien.setText(tongtien+"");
    }//GEN-LAST:event_btnUpThitActionPerformed

    private void btnDownQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownQuayActionPerformed
        int a = Integer.parseInt(lbQuay.getText());
        long tong;
        if (a==0){
            lbQuay.setText(countQuay+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbQuay.setText((--countQuay)+"");
            tong=5000*countQuay;
            lbTongQuay.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownQuayActionPerformed

    private void btnDownHGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownHGActionPerformed
        int a = Integer.parseInt(lbHG.getText());
        long tong;
        if (a==0){
            lbHG.setText(countHG+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbHG.setText((--countHG)+"");
            tong=5000*countHG;
            lbTongHG.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownHGActionPerformed

    private void btnDownBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownBPActionPerformed
        int a = Integer.parseInt(lbBP.getText());
        long tong;
        if (a==0){
            lbBP.setText(countBP+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbBP.setText((--countBP)+"");
            tong=10000*countBP;
            lbTongBP.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownBPActionPerformed

    private void btnDownTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownTietActionPerformed
        int a = Integer.parseInt(lbTiet.getText());
        long tong;
        if (a==0){
            lbTiet.setText(countTiet+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbTiet.setText((--countTiet)+"");
            tong=10000*countTiet;
            lbTongTiet.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownTietActionPerformed

    private void btnDownTHGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownTHGActionPerformed
        int a = Integer.parseInt(lbTHG.getText());
        long tong;
        if (a==0){
            lbTHG.setText(countTHG+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbTHG.setText((--countTHG)+"");
            tong=15000*countTHG;
            lbTongTHG.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownTHGActionPerformed

    private void btnDownThitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownThitActionPerformed
        int a = Integer.parseInt(lbThit.getText());
        long tong;
        if (a==0){
            lbThit.setText(countThit+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
        else {
            lbThit.setText((--countThit)+"");
            tong=25000*countThit;
            lbTongThit.setText(tong+"");
            tongtien=75000*countDB+60000*countLON+45000*countNHO+5000*countQuay+5000*countHG+10000*countBP+10000*countTiet+15000*countTHG+25000*countThit;
            lbTongTien.setText(tongtien+"");
        }
    }//GEN-LAST:event_btnDownThitActionPerformed

    private void lbSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbSPFocusLost
        if (GoiMonBUS.checkSoPhieu(lbSP.getText())){
            Random rd = new Random();
            int n = rd.nextInt(999999);
            lbSP.setText(n + "");
        }
    }//GEN-LAST:event_lbSPFocusLost

    private void txtBanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBanFocusLost
        
    }//GEN-LAST:event_txtBanFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int abc = Integer.parseInt(txtBan.getText());
        if (txtBan.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số bàn !");
            txtBan.requestFocus();
        }
        else if (abc < 1 || abc > 30){
            JOptionPane.showMessageDialog(rootPane, "Số bàn không hợp lệ !");
            txtBan.setText("");
            txtBan.requestFocus();
        }
        else if (GoiMonBUS.checkBan(txtBan.getText())){
            JOptionPane.showMessageDialog(rootPane, "Bàn có khách !");
            txtBan.setText("");
            txtBan.requestFocus();
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Bàn trống !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDownBP;
    private javax.swing.JButton btnDownDB;
    private javax.swing.JButton btnDownHG;
    private javax.swing.JButton btnDownLON;
    private javax.swing.JButton btnDownNHO;
    private javax.swing.JButton btnDownQuay;
    private javax.swing.JButton btnDownTHG;
    private javax.swing.JButton btnDownThit;
    private javax.swing.JButton btnDownTiet;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnUpBP;
    private javax.swing.JButton btnUpDB;
    private javax.swing.JButton btnUpHG;
    private javax.swing.JButton btnUpLON;
    private javax.swing.JButton btnUpNHO;
    private javax.swing.JButton btnUpQuay;
    private javax.swing.JButton btnUpTHG;
    private javax.swing.JButton btnUpThit;
    private javax.swing.JButton btnUpTiet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbBP;
    private javax.swing.JLabel lbDB;
    private javax.swing.JLabel lbHG;
    private javax.swing.JLabel lbLON;
    private javax.swing.JLabel lbNHO;
    private javax.swing.JLabel lbQuay;
    private javax.swing.JLabel lbSP;
    private javax.swing.JLabel lbTHG;
    private javax.swing.JLabel lbThit;
    private javax.swing.JLabel lbTiet;
    private javax.swing.JLabel lbTongBP;
    private javax.swing.JLabel lbTongDB;
    private javax.swing.JLabel lbTongHG;
    private javax.swing.JLabel lbTongLON;
    private javax.swing.JLabel lbTongNHO;
    private javax.swing.JLabel lbTongQuay;
    private javax.swing.JLabel lbTongTHG;
    private javax.swing.JLabel lbTongThit;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbTongTiet;
    private javax.swing.JTextField txtBan;
    // End of variables declaration//GEN-END:variables
}
